'''my_list=[1,2,3,4]
print(*my_list,end="@,")
my_list
my_list.append(9999)
print(*my_list)
my_list.pop()'''
#print(my_list)
#my_list_2=[5,6,7,8]
#new_lst=my_list+my_list_2
#print(*new_lst)
#new_lst.pop()
#print(*new_lst)
#cnt=my_list.count(2)
#print(cnt)
my_list=[2,3,5,51,74,8,11,23,45,55,7]
my_list.sort()
print(*my_list)
my_list=list(map(str,input().split("@")))
print(*my_list)
